version: '3.8'
services:
  minecraft:
    image: 'itzg/minecraft-server:java19'
    volumes:
      - './.local/data:/data'
    ports:
      - '8123:8123'  # dynmap
      - '25565:25565'
    environment:
      TZ: 'Asia/Tokyo'
      TYPE: 'SPIGOT'
      VERSION: '1.19.4'
      MAX_MEMORY: '4G'
      EULA: 'TRUE'
      OPS: "${MINECRAFT_OPS_PLAYER_ID}"
      MOTD: 'A Minecraft Server for vim-jp!'
      ICON: 'https://raw.githubusercontent.com/vim-jp/slack-icon/master/20200515-alicia-edited/icon_light-500x500.png'
      SPAWN_PROTECTION: '0'
      OVERRIDE_SERVER_PROPERTIES: 'true'
    restart: 'unless-stopped'
    cpus: 4.0
