name: 'MODal'
main: 'org.vim_jp.modal.MODalPlugin'
version: '0.1.0'
api-version: '1.20'
libraries:
  - 'org.scala-lang:scala3-library_3:3.3.0'
commands:
  change:
    description: Change mode of the player
    usage: "Usage: /<command> [mode]"
  inactivate:
    descritpion: Inactivate mode of the player
    usage: "Usage: /<command>"
